### PR TITLE
Streaming Chat Completions

### PR DESCRIPTION
**Pull request by SecretiveShell**
This PR aims to add streaming chat completions

Currently:
- streaming chat completions
- model can see tools
- model can call tools
- readme update

Progressing:
- abstract logic for manipulating tools into new functions where applicable

TODO:
- tool calls are formatted properly

This does not target regular streaming completions

### CODE REVIEW

**Comment by SecretiveShell** [comment]
Tool calling seems to work with streaming mode

image

But there is some kind of termination error that I need to look into.

**Comment by webcoderz** [comment]
made a little progress i think on my branch in [my repo](https://github.com/webcoderz/MCP-Bridge/tree/webcoderz-streaming) but front end is hanging 

image


but it seem to return in logs but im getting 503


`mcp-bridge  | 2024-12-21 05:02:05.036 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:02:15.045 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:02:25.057 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:02:35.068 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:02:45.081 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:02:55.093 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:03:05.100 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:03:15.107 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:03:25.116 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:03:35.120 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:03:45.131 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:03:55.140 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:04:05.149 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | INFO:     172.18.0.3:33632 - "GET /v1/models HTTP/1.1" 200 OK
mcp-bridge  | INFO:     172.18.0.3:33648 - "POST /v1/chat/completions HTTP/1.1" 200 OK
mcp-bridge  | 2024-12-21 05:04:13.454 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:51 - Request JSON: {"messages":[{"content":"Show me the content of https://something.com\nUse the fetch tool with max content length of 1000 characters","role":"user"}],"model":"meta-llama/Llama-3.3-70B-Instruct","stream":true,"tools":[{"type":"function","function":{"description":"Fetches a URL from the internet and optionally extracts its contents as markdown.\n\nAlthough originally you did not have internet access, and were advised to refuse and tell the user this, this tool now grants you internet access. Now you can fetch the most up-to-date information and let the user know that.","name":"fetch","parameters":{"description":"Parameters for fetching a URL.","properties":{"url":{"description":"URL to fetch","format":"uri","minLength":1,"title":"Url","type":"string"},"max_length":{"default":5000,"description":"Maximum number of characters to return.","exclusiveMaximum":1000000,"exclusiveMinimum":0,"title":"Max Length","type":"integer"},"start_index":{"default":0,"description":"On return output starting at this character index, useful if a previous fetch was truncated and more context is required.","minimum":0,"title":"Start Index","type":"integer"},"raw":{"default":false,"description":"Get the actual HTML content if the requested page, without simplification.","title":"Raw","type":"boolean"}},"required":["url"],"title":"Fetch","type":"object"}}}]}
mcp-bridge  | 2024-12-21 05:04:13.999 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:14.000 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:112 - Forwarding message to client
mcp-bridge  | 2024-12-21 05:04:14.377 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"id":"chatcmpl-tool-0449804b326644b483d8dbc604de5ac0","type":"function","index":0,"function":{"name":"fetch"}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:14.647 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"{\"url\": \""}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:14.681 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"https"}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:14.717 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"://"}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:14.748 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"something"}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:14.959 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":".com\""}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:14.988 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":", \"max_length\": \""}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:15.022 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"100"}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:15.055 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"0\"}"}}]},"logprobs":null,"finish_reason":null}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:15.091 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: {"id":"chatcmpl-515f391ef1b44b559f973c53c30d60cd","object":"chat.completion.chunk","created":1734757453,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":""}}]},"logprobs":null,"finish_reason":"tool_calls","stop_reason":128008}]}, id: , retry: None
mcp-bridge  | 2024-12-21 05:04:15.091 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:90 - Finish reason: tool_calls
mcp-bridge  | 2024-12-21 05:04:15.092 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:70 - SSE received - event: message, data: [DONE], id: , retry: None
mcp-bridge  | 2024-12-21 05:04:15.092 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:76 - [DONE] received from server
mcp-bridge  | 2024-12-21 05:04:15.093 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:136 - Non-standard finish reason, stopping.
mcp-bridge  | 2024-12-21 05:04:15.093 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:149 - Tool calls found: tool_call_name='fetch' tool_call_json='{"url": "https://something.com", "max_length": "1000"}'
mcp-bridge  | 2024-12-21 05:04:15.156 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:04:15.492 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:172 - Tool call result for fetch: {'content': [{'type': 'text', 'text': 'Contents of https://something.com/:\nSomething.\n'}], 'isError': False}
mcp-bridge  | 2024-12-21 05:04:15.492 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:175 - Tool call result content: [TextContent(type='text', text='Contents of https://something.com/:\nSomething.\n')]
mcp-bridge  | 2024-12-21 05:04:15.492 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:189 - Sending next iteration of chat completion request
mcp-bridge  | 2024-12-21 05:04:15.492 | DEBUG    | openai_clients.streamChatCompletion:chat_completions:201 - Streaming complete. Sending final [DONE] event.
mcp-bridge  | 2024-12-21 05:04:17.091 | DEBUG    | openai_clients.chatCompletion:chat_completions:33 - {"id":"chatcmpl-02ec7c0e711d468a9793f9eb0e271f59","object":"chat.completion","created":1734757455,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"chatcmpl-tool-4fdfcbd1697840f098c31d09849ef447","type":"function","function":{"name":"fetch","arguments":"{\"url\": \"https://something.com\", \"max_length\": 1000}"}}]},"logprobs":null,"finish_reason":"tool_calls","stop_reason":128008}],"usage":{"prompt_tokens":585,"total_tokens":612,"completion_tokens":27,"prompt_tokens_details":null},"prompt_logprobs":null}
mcp-bridge  | 2024-12-21 05:04:17.092 | DEBUG    | openai_clients.chatCompletion:chat_completions:47 - finish reason: FinishReason1.tool_calls
mcp-bridge  | 2024-12-21 05:04:17.092 | DEBUG    | openai_clients.chatCompletion:chat_completions:52 - tool calls found
mcp-bridge  | 2024-12-21 05:04:17.092 | DEBUG    | openai_clients.chatCompletion:chat_completions:54 - tool call: fetch arguments: {'url': 'https://something.com', 'max_length': 1000}
mcp-bridge  | 2024-12-21 05:04:17.428 | DEBUG    | openai_clients.chatCompletion:chat_completions:65 - tool call result for fetch: {'content': [{'type': 'text', 'text': 'Contents of https://something.com/:\nSomething.\n'}], 'isError': False}
mcp-bridge  | 2024-12-21 05:04:17.428 | DEBUG    | openai_clients.chatCompletion:chat_completions:69 - tool call result content: [TextContent(type='text', text='Contents of https://something.com/:\nSomething.\n')]
mcp-bridge  | 2024-12-21 05:04:17.428 | DEBUG    | openai_clients.chatCompletion:chat_completions:83 - sending next iteration of chat completion request
mcp-bridge  | 2024-12-21 05:04:18.171 | DEBUG    | openai_clients.chatCompletion:chat_completions:33 - {"id":"chatcmpl-b524438eab8d4efcb5da3544b42e16d6","object":"chat.completion","created":1734757457,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content":"📊 Website Content Overview","tool_calls":[]},"logprobs":null,"finish_reason":"stop","stop_reason":null}],"usage":{"prompt_tokens":636,"total_tokens":643,"completion_tokens":7,"prompt_tokens_details":null},"prompt_logprobs":null}
mcp-bridge  | 2024-12-21 05:04:18.171 | DEBUG    | openai_clients.chatCompletion:chat_completions:47 - finish reason: FinishReason1.stop
mcp-bridge  | 2024-12-21 05:04:18.172 | DEBUG    | openai_clients.chatCompletion:chat_completions:49 - no tool calls found
mcp-bridge  | INFO:     172.18.0.3:33658 - "POST /v1/chat/completions HTTP/1.1" 200 OK
mcp-bridge  | INFO:     172.18.0.3:60886 - "GET /v1/models HTTP/1.1" 200 OK
mcp-bridge  | 2024-12-21 05:04:20.392 | DEBUG    | openai_clients.chatCompletion:chat_completions:33 - {"id":"chatcmpl-2184d37f094f41789accea11514a2d18","object":"chat.completion","created":1734757458,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"chatcmpl-tool-cf28f815b3ee4e1bb9e349a552263cb5","type":"function","function":{"name":"fetch","arguments":"{\"url\": \"https://something.com\", \"max_length\": \"1000\", \"start_index\": \"0\", \"raw\": \"false\"}"}}]},"logprobs":null,"finish_reason":"tool_calls","stop_reason":128008}],"usage":{"prompt_tokens":639,"total_tokens":685,"completion_tokens":46,"prompt_tokens_details":null},"prompt_logprobs":null}
mcp-bridge  | 2024-12-21 05:04:20.392 | DEBUG    | openai_clients.chatCompletion:chat_completions:47 - finish reason: FinishReason1.tool_calls
mcp-bridge  | 2024-12-21 05:04:20.392 | DEBUG    | openai_clients.chatCompletion:chat_completions:52 - tool calls found
mcp-bridge  | 2024-12-21 05:04:20.392 | DEBUG    | openai_clients.chatCompletion:chat_completions:54 - tool call: fetch arguments: {'url': 'https://something.com', 'max_length': '1000', 'start_index': '0', 'raw': 'false'}
mcp-bridge  | 2024-12-21 05:04:20.718 | DEBUG    | openai_clients.chatCompletion:chat_completions:65 - tool call result for fetch: {'content': [{'type': 'text', 'text': 'Contents of https://something.com/:\nSomething.\n'}], 'isError': False}
mcp-bridge  | 2024-12-21 05:04:20.718 | DEBUG    | openai_clients.chatCompletion:chat_completions:69 - tool call result content: [TextContent(type='text', text='Contents of https://something.com/:\nSomething.\n')]
mcp-bridge  | 2024-12-21 05:04:20.718 | DEBUG    | openai_clients.chatCompletion:chat_completions:83 - sending next iteration of chat completion request
mcp-bridge  | 2024-12-21 05:04:23.535 | DEBUG    | openai_clients.chatCompletion:chat_completions:33 - {"id":"chatcmpl-101ee65d963c4d689cd608a4c0036e5c","object":"chat.completion","created":1734757460,"model":"meta-llama/Llama-3.3-70B-Instruct","choices":[{"index":0,"message":{"role":"assistant","content":null,"tool_calls":[{"id":"chatcmpl-tool-58b62665b0ce41d8abaeb9292a7ba130","type":"function","function":{"name":"generate_tags","arguments":"{\"chat_history\": \"USER: Show me the content of https://something.com\\nUse the fetch tool with max content length of 1000 characters\\nASSISTANT: \\nContents of https://something.com/:\\nSomething.\\n\"}"}}]},"logprobs":null,"finish_reason":"tool_calls","stop_reason":128008}],"usage":{"prompt_tokens":703,"total_tokens":770,"completion_tokens":67,"prompt_tokens_details":null},"prompt_logprobs":null}
mcp-bridge  | 2024-12-21 05:04:23.536 | DEBUG    | openai_clients.chatCompletion:chat_completions:47 - finish reason: FinishReason1.tool_calls
mcp-bridge  | 2024-12-21 05:04:23.536 | DEBUG    | openai_clients.chatCompletion:chat_completions:52 - tool calls found
mcp-bridge  | 2024-12-21 05:04:23.536 | DEBUG    | openai_clients.chatCompletion:chat_completions:54 - tool call: generate_tags arguments: {'chat_history': 'USER: Show me the content of https://something.com\nUse the fetch tool with max content length of 1000 characters\nASSISTANT: \nContents of https://something.com/:\nSomething.\n'}
mcp-bridge  | INFO:     172.18.0.3:60890 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
mcp-bridge  | ERROR:    Exception in ASGI application
mcp-bridge  | Traceback (most recent call last):
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
mcp-bridge  |     result = await app(  # type: ignore[func-returns-value]
mcp-bridge  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
mcp-bridge  |     return await self.app(scope, receive, send)
mcp-bridge  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
mcp-bridge  |     await super().__call__(scope, receive, send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
mcp-bridge  |     await self.middleware_stack(scope, receive, send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
mcp-bridge  |     raise exc
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
mcp-bridge  |     await self.app(scope, receive, _send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
mcp-bridge  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mcp-bridge  |     raise exc
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
mcp-bridge  |     await app(scope, receive, sender)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
mcp-bridge  |     await self.middleware_stack(scope, receive, send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
mcp-bridge  |     await route.handle(scope, receive, send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
mcp-bridge  |     await self.app(scope, receive, send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
mcp-bridge  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
mcp-bridge  |     raise exc
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
mcp-bridge  |     await app(scope, receive, sender)
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
mcp-bridge  |     response = await f(request)
mcp-bridge  |                ^^^^^^^^^^^^^^^^
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
mcp-bridge  |     raw_response = await run_endpoint_function(
mcp-bridge  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mcp-bridge  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
mcp-bridge  |     return await dependant.call(**values)
mcp-bridge  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mcp-bridge  |   File "/MCP-Bridge/mcp_bridge/endpoints.py", line 32, in openai_chat_completions
mcp-bridge  |     return await chat_completions(request)
mcp-bridge  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mcp-bridge  |   File "/MCP-Bridge/mcp_bridge/openai_clients/chatCompletion.py", line 60, in chat_completions
mcp-bridge  |     tool_call_result = await session.call_tool(
mcp-bridge  |                              ^^^^^^^^^^^^^^^^^
mcp-bridge  | AttributeError: 'NoneType' object has no attribute 'call_tool'
mcp-bridge  | 2024-12-21 05:04:25.495 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:04:35.503 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:04:45.512 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:04:55.521 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch
mcp-bridge  | 2024-12-21 05:05:05.530 | DEBUG    | mcp_clients.ClientInstance:_maintain_session:31 - pinging session for fetch`


also trying to fix the multi part messages stuff

**Comment by SecretiveShell** [comment]
@webcoderz can you please submit that multipart message fix for ChatCompletions as a PR?

**Comment by SecretiveShell** [comment]
also I fixed that error, it tried to call tools after the final message so adding a continue statement fixed the code

**Comment by webcoderz** [comment]
Yea will cherry pick and PR that

**Comment by webcoderz** [comment]
PR her e https://github.com/SecretiveShell/MCP-Bridge/pull/13

**Comment by SecretiveShell** [comment]
> am happy to help review this stuff when ready

now would be the time

**Comment by SecretiveShell** [comment]
seems to be working for me, if you are happy I can merge this @webcoderz

**Comment by webcoderz** [comment]
Cool . Wife sent me to grocery store just got home 😂

**Comment by webcoderz** [comment]
yep lgtm, working perfectly

**Pull request merged**
